[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rew = "DHdbzP1fvKzcCVmyseygBmWjQL3NTWqcEK87LUrLbUf9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mb/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
